# Generated by Django 3.0.2 on 2020-02-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sender_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
