# Generated by Django 3.0.2 on 2020-02-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200222_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
