# Generated by Django 3.0.2 on 2020-02-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200222_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='file',
            field=models.FileField(upload_to='media/am/'),
        ),
    ]
