# Generated by Django 3.0.2 on 2020-02-22 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200222_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='otp',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
